#pragma once

namespace app::game
{
	class MsgActionModeEnd : public hh::fnd::MessageAsyncHandlerInplace<MsgActionModeEnd>, public fnd::AppMessage<MsgActionModeEnd>
	{
	private:
		inline static uint32_t MessageID = 0x2002;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgActionModeEnd() /* : fnd::AppMessage<MsgActionModeEnd>(MessageID) */ = delete;
	};
}