#pragma once

namespace app::camera
{
	class MsgActionCamera : public hh::fnd::MessageAsyncHandlerInplace<MsgActionCamera>, public fnd::AppMessage<MsgActionCamera>
	{
	private:
		inline static uint32_t MessageID = 0x2001;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgActionCamera() /* : fnd::AppMessage<MsgActionCamera>(MessageID) */ = delete;
	};
}