#pragma once

namespace app
{
	class MsgAttackGroundBullet : public hh::fnd::MessageAsyncHandlerInplace<MsgAttackGroundBullet>, public fnd::AppMessage<MsgAttackGroundBullet>
	{
	private:
		inline static uint32_t MessageID = 0x2015;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgAttackGroundBullet() /* : fnd::AppMessage<MsgAttackGroundBullet>(MessageID) */ = delete;
	};
}