#pragma once

namespace app::player
{
	class MsgBeginBallMove : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginBallMove>, public fnd::AppMessage<MsgBeginBallMove>
	{
	private:
		inline static uint32_t MessageID = 0x2025;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBeginBallMove() /* : fnd::AppMessage<MsgBeginBallMove>(MessageID) */ = delete;
	};
}