#pragma once

namespace app
{
	class MsgBeeDamage : public hh::fnd::MessageAsyncHandlerInplace<MsgBeeDamage>, public fnd::AppMessage<MsgBeeDamage>
	{
	private:
		inline static uint32_t MessageID = 0x201F;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBeeDamage() /* : fnd::AppMessage<MsgBeeDamage>(MessageID) */ = delete;
	};
}