#pragma once

namespace app::player
{
	class MsgBeginDimension : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginDimension>, public fnd::AppMessage<MsgBeginDimension>
	{
	private:
		inline static uint32_t MessageID = 0x2035;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(72);

		MsgBeginDimension() /* : fnd::AppMessage<MsgBeginDimension>(MessageID) */ = delete;
	};
}