#pragma once

namespace app
{
	class MsgBossDragonDisableBullet : public hh::fnd::MessageAsyncHandlerInplace<MsgBossDragonDisableBullet>, public fnd::AppMessage<MsgBossDragonDisableBullet>
	{
	private:
		inline static uint32_t MessageID = 0x206E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBossDragonDisableBullet() /* : fnd::AppMessage<MsgBossDragonDisableBullet>(MessageID) */ = delete;
	};
}