#pragma once

namespace app::player
{
	class MsgBeginQuickStep : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginQuickStep>, public fnd::AppMessage<MsgBeginQuickStep>
	{
	private:
		inline static uint32_t MessageID = 0x2049;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(120);

		MsgBeginQuickStep() /* : fnd::AppMessage<MsgBeginQuickStep>(MessageID) */ = delete;
	};
}