#pragma once

namespace app
{
	class MsgBoostLimited2DMove : public hh::fnd::MessageAsyncHandlerInplace<MsgBoostLimited2DMove>, public fnd::AppMessage<MsgBoostLimited2DMove>
	{
	private:
		inline static uint32_t MessageID = 0x2059;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgBoostLimited2DMove() /* : fnd::AppMessage<MsgBoostLimited2DMove>(MessageID) */ = delete;
	};
}