#pragma once

namespace app
{
	class MsgBeginBossBattle : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginBossBattle>, public fnd::AppMessage<MsgBeginBossBattle>
	{
	private:
		inline static uint32_t MessageID = 0x202A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(120);

		MsgBeginBossBattle() /* : fnd::AppMessage<MsgBeginBossBattle>(MessageID) */ = delete;
	};
}