#pragma once

namespace app
{
	class MsgBossDragonCameraChange : public hh::fnd::MessageAsyncHandlerInplace<MsgBossDragonCameraChange>, public fnd::AppMessage<MsgBossDragonCameraChange>
	{
	private:
		inline static uint32_t MessageID = 0x206C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(48);

		MsgBossDragonCameraChange() /* : fnd::AppMessage<MsgBossDragonCameraChange>(MessageID) */ = delete;
	};
}