#pragma once

namespace app
{
	class MsgBossBitEndWaveAreaRotation : public hh::fnd::MessageAsyncHandlerInplace<MsgBossBitEndWaveAreaRotation>, public fnd::AppMessage<MsgBossBitEndWaveAreaRotation>
	{
	private:
		inline static uint32_t MessageID = 0x2064;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBossBitEndWaveAreaRotation() /* : fnd::AppMessage<MsgBossBitEndWaveAreaRotation>(MessageID) */ = delete;
	};
}