#pragma once

namespace app
{
	class MsgBossDragonNotifyInvadeSub : public hh::fnd::MessageAsyncHandlerInplace<MsgBossDragonNotifyInvadeSub>, public fnd::AppMessage<MsgBossDragonNotifyInvadeSub>
	{
	private:
		inline static uint32_t MessageID = 0x2071;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBossDragonNotifyInvadeSub() /* : fnd::AppMessage<MsgBossDragonNotifyInvadeSub>(MessageID) */ = delete;
	};
}