#pragma once

namespace app
{
	class MsgBossBitFormationChange : public hh::fnd::MessageAsyncHandlerInplace<MsgBossBitFormationChange>, public fnd::AppMessage<MsgBossBitFormationChange>
	{
	private:
		inline static uint32_t MessageID = 0x2065;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgBossBitFormationChange() /* : fnd::AppMessage<MsgBossBitFormationChange>(MessageID) */ = delete;
	};
}