#pragma once

namespace app
{
	class MsgBossKnightShieldRideDamage : public hh::fnd::MessageAsyncHandlerInplace<MsgBossKnightShieldRideDamage>, public fnd::AppMessage<MsgBossKnightShieldRideDamage>
	{
	private:
		inline static uint32_t MessageID = 0x207E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBossKnightShieldRideDamage() /* : fnd::AppMessage<MsgBossKnightShieldRideDamage>(MessageID) */ = delete;
	};
}