#pragma once

namespace app
{
	class MsgBeginedBossBattle : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginedBossBattle>, public fnd::AppMessage<MsgBeginedBossBattle>
	{
	private:
		inline static uint32_t MessageID = 0x2037;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBeginedBossBattle() /* : fnd::AppMessage<MsgBeginedBossBattle>(MessageID) */ = delete;
	};
}