#pragma once

namespace app
{
	class MsgBossRifleBeastBeginFingerSnap : public hh::fnd::MessageAsyncHandlerInplace<MsgBossRifleBeastBeginFingerSnap>, public fnd::AppMessage<MsgBossRifleBeastBeginFingerSnap>
	{
	private:
		inline static uint32_t MessageID = 0x208C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgBossRifleBeastBeginFingerSnap() /* : fnd::AppMessage<MsgBossRifleBeastBeginFingerSnap>(MessageID) */ = delete;
	};
}