#pragma once

namespace app
{
	class MsgBossLaserParry : public hh::fnd::MessageAsyncHandlerInplace<MsgBossLaserParry>, public fnd::AppMessage<MsgBossLaserParry>
	{
	private:
		inline static uint32_t MessageID = 0x2084;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(56);

		MsgBossLaserParry() /* : fnd::AppMessage<MsgBossLaserParry>(MessageID) */ = delete;
	};
}