#pragma once

namespace app
{
	class MsgBossKnightBattle2ShieldResult : public hh::fnd::MessageAsyncHandlerInplace<MsgBossKnightBattle2ShieldResult>, public fnd::AppMessage<MsgBossKnightBattle2ShieldResult>
	{
	private:
		inline static uint32_t MessageID = 0x207A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgBossKnightBattle2ShieldResult() /* : fnd::AppMessage<MsgBossKnightBattle2ShieldResult>(MessageID) */ = delete;
	};
}