#pragma once

namespace app::game
{
	class MsgBattleRushDefeatEnemy : public hh::fnd::MessageAsyncHandlerInplace<MsgBattleRushDefeatEnemy>, public fnd::AppMessage<MsgBattleRushDefeatEnemy>
	{
	private:
		inline static uint32_t MessageID = 0x201E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgBattleRushDefeatEnemy() /* : fnd::AppMessage<MsgBattleRushDefeatEnemy>(MessageID) */ = delete;
	};
}