#pragma once

namespace app::player
{
	class MsgBeginTreadmill : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginTreadmill>, public fnd::AppMessage<MsgBeginTreadmill>
	{
	private:
		inline static uint32_t MessageID = 0x2050;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgBeginTreadmill() /* : fnd::AppMessage<MsgBeginTreadmill>(MessageID) */ = delete;
	};
}