#pragma once

namespace app
{
	class MsgBossRifleBeastSpritBomb : public hh::fnd::MessageAsyncHandlerInplace<MsgBossRifleBeastSpritBomb>, public fnd::AppMessage<MsgBossRifleBeastSpritBomb>
	{
	private:
		inline static uint32_t MessageID = 0x2098;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgBossRifleBeastSpritBomb() /* : fnd::AppMessage<MsgBossRifleBeastSpritBomb>(MessageID) */ = delete;
	};
}