#pragma once

namespace app::player
{
	class MsgBeginSlider : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginSlider>, public fnd::AppMessage<MsgBeginSlider>
	{
	private:
		inline static uint32_t MessageID = 0x204D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgBeginSlider() /* : fnd::AppMessage<MsgBeginSlider>(MessageID) */ = delete;
	};
}