#pragma once

namespace app::game
{
	class MsgBeginPracticeGuide : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginPracticeGuide>, public fnd::AppMessage<MsgBeginPracticeGuide>
	{
	private:
		inline static uint32_t MessageID = 0x2045;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgBeginPracticeGuide() /* : fnd::AppMessage<MsgBeginPracticeGuide>(MessageID) */ = delete;
	};
}