#pragma once

namespace app::player
{
	class MsgBeginBossCounter : public hh::fnd::MessageAsyncHandlerInplace<MsgBeginBossCounter>, public fnd::AppMessage<MsgBeginBossCounter>
	{
	private:
		inline static uint32_t MessageID = 0x202E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgBeginBossCounter() /* : fnd::AppMessage<MsgBeginBossCounter>(MessageID) */ = delete;
	};
}