#pragma once

namespace app::camera
{
	class MsgBossBlowOffCamera : public hh::fnd::MessageAsyncHandlerInplace<MsgBossBlowOffCamera>, public fnd::AppMessage<MsgBossBlowOffCamera>
	{
	private:
		inline static uint32_t MessageID = 0x206A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgBossBlowOffCamera() /* : fnd::AppMessage<MsgBossBlowOffCamera>(MessageID) */ = delete;
	};
}