#pragma once

namespace app::player
{
	class MsgChangeStateBossCounter : public hh::fnd::MessageAsyncHandlerInplace<MsgChangeStateBossCounter>, public fnd::AppMessage<MsgChangeStateBossCounter>
	{
	private:
		inline static uint32_t MessageID = 0x20CC;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgChangeStateBossCounter() /* : fnd::AppMessage<MsgChangeStateBossCounter>(MessageID) */ = delete;
	};
}