#pragma once

namespace app::camera
{
	class MsgCameraZoomEnd : public hh::fnd::MessageAsyncHandlerInplace<MsgCameraZoomEnd>, public fnd::AppMessage<MsgCameraZoomEnd>
	{
	private:
		inline static uint32_t MessageID = 0x20AE;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgCameraZoomEnd() /* : fnd::AppMessage<MsgCameraZoomEnd>(MessageID) */ = delete;
	};
}