#pragma once

namespace app::camera
{
	class MsgCameraMoveLocalTransform : public hh::fnd::MessageAsyncHandlerInplace<MsgCameraMoveLocalTransform>, public fnd::AppMessage<MsgCameraMoveLocalTransform>
	{
	private:
		inline static uint32_t MessageID = 0x20A0;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgCameraMoveLocalTransform() /* : fnd::AppMessage<MsgCameraMoveLocalTransform>(MessageID) */ = delete;
	};
}