#pragma once

namespace app
{
	class MsgCharacterSetLookAt : public hh::fnd::MessageAsyncHandlerInplace<MsgCharacterSetLookAt>, public fnd::AppMessage<MsgCharacterSetLookAt>
	{
	private:
		inline static uint32_t MessageID = 0x20D2;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgCharacterSetLookAt() /* : fnd::AppMessage<MsgCharacterSetLookAt>(MessageID) */ = delete;
	};
}