#pragma once

namespace app
{
	class MsgCyloopLevitateActivate : public hh::fnd::MessageAsyncHandlerInplace<MsgCyloopLevitateActivate>, public fnd::AppMessage<MsgCyloopLevitateActivate>
	{
	private:
		inline static uint32_t MessageID = 0x20E9;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgCyloopLevitateActivate() /* : fnd::AppMessage<MsgCyloopLevitateActivate>(MessageID) */ = delete;
	};
}