#pragma once

namespace app::camera
{
	class MsgCameraBoardingJump : public hh::fnd::MessageAsyncHandlerInplace<MsgCameraBoardingJump>, public fnd::AppMessage<MsgCameraBoardingJump>
	{
	private:
		inline static uint32_t MessageID = 0x209B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgCameraBoardingJump() /* : fnd::AppMessage<MsgCameraBoardingJump>(MessageID) */ = delete;
	};
}