#pragma once

namespace app
{
	class MsgCollisionEnterInCyBlaster : public hh::fnd::MessageAsyncHandlerInplace<MsgCollisionEnterInCyBlaster>, public fnd::AppMessage<MsgCollisionEnterInCyBlaster>
	{
	private:
		inline static uint32_t MessageID = 0x20DA;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(56);

		MsgCollisionEnterInCyBlaster() /* : fnd::AppMessage<MsgCollisionEnterInCyBlaster>(MessageID) */ = delete;
	};
}