#pragma once

namespace app::camera
{
	class MsgCameraLockonTarget : public hh::fnd::MessageAsyncHandlerInplace<MsgCameraLockonTarget>, public fnd::AppMessage<MsgCameraLockonTarget>
	{
	private:
		inline static uint32_t MessageID = 0x209F;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgCameraLockonTarget() /* : fnd::AppMessage<MsgCameraLockonTarget>(MessageID) */ = delete;
	};
}