#pragma once

namespace app::camera
{
	class MsgCameraZoomBegin : public hh::fnd::MessageAsyncHandlerInplace<MsgCameraZoomBegin>, public fnd::AppMessage<MsgCameraZoomBegin>
	{
	private:
		inline static uint32_t MessageID = 0x20AD;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgCameraZoomBegin() /* : fnd::AppMessage<MsgCameraZoomBegin>(MessageID) */ = delete;
	};
}