#pragma once

namespace app
{
	class MsgChangeSuperSonic2 : public hh::fnd::MessageAsyncHandlerInplace<MsgChangeSuperSonic2>, public fnd::AppMessage<MsgChangeSuperSonic2>
	{
	private:
		inline static uint32_t MessageID = 0x20CD;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgChangeSuperSonic2() /* : fnd::AppMessage<MsgChangeSuperSonic2>(MessageID) */ = delete;
	};
}