#pragma once

namespace app
{
	class MsgChangeLimited2DMoveParameter : public hh::fnd::MessageAsyncHandlerInplace<MsgChangeLimited2DMoveParameter>, public fnd::AppMessage<MsgChangeLimited2DMoveParameter>
	{
	private:
		inline static uint32_t MessageID = 0x20C5;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgChangeLimited2DMoveParameter() /* : fnd::AppMessage<MsgChangeLimited2DMoveParameter>(MessageID) */ = delete;
	};
}