#pragma once

namespace app::player
{
	class MsgDivingChangeSpeed : public hh::fnd::MessageAsyncHandlerInplace<MsgDivingChangeSpeed>, public fnd::AppMessage<MsgDivingChangeSpeed>
	{
	private:
		inline static uint32_t MessageID = 0x2109;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgDivingChangeSpeed() /* : fnd::AppMessage<MsgDivingChangeSpeed>(MessageID) */ = delete;
	};
}