#pragma once

namespace app::evt
{
	class MsgDvGeneralTrigger : public hh::fnd::MessageAsyncHandlerInplace<MsgDvGeneralTrigger>, public fnd::AppMessage<MsgDvGeneralTrigger>
	{
	private:
		inline static uint32_t MessageID = 0x210E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgDvGeneralTrigger() /* : fnd::AppMessage<MsgDvGeneralTrigger>(MessageID) */ = delete;
	};
}