#pragma once

namespace app::player
{
	class MsgDead : public hh::fnd::MessageAsyncHandlerInplace<MsgDead>, public fnd::AppMessage<MsgDead>
	{
	private:
		inline static uint32_t MessageID = 0x20ED;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgDead() /* : fnd::AppMessage<MsgDead>(MessageID) */ = delete;
	};
}