#pragma once

namespace app::game
{
	class MsgDebugNotifyWarp : public hh::fnd::MessageAsyncHandlerInplace<MsgDebugNotifyWarp>, public fnd::AppMessage<MsgDebugNotifyWarp>
	{
	private:
		inline static uint32_t MessageID = 0x20F9;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgDebugNotifyWarp() /* : fnd::AppMessage<MsgDebugNotifyWarp>(MessageID) */ = delete;
	};
}