#pragma once

namespace app
{
	class MsgEndWaterFall : public hh::fnd::MessageAsyncHandlerInplace<MsgEndWaterFall>, public fnd::AppMessage<MsgEndWaterFall>
	{
	private:
		inline static uint32_t MessageID = 0x215F;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndWaterFall() /* : fnd::AppMessage<MsgEndWaterFall>(MessageID) */ = delete;
	};
}