#pragma once

namespace app
{
	class MsgEndQuest : public hh::fnd::MessageAsyncHandlerInplace<MsgEndQuest>, public fnd::AppMessage<MsgEndQuest>
	{
	private:
		inline static uint32_t MessageID = 0x2145;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndQuest() /* : fnd::AppMessage<MsgEndQuest>(MessageID) */ = delete;
	};
}