#pragma once

namespace app::player
{
	class MsgEndAccelRail : public hh::fnd::MessageAsyncHandlerInplace<MsgEndAccelRail>, public fnd::AppMessage<MsgEndAccelRail>
	{
	private:
		inline static uint32_t MessageID = 0x2115;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndAccelRail() /* : fnd::AppMessage<MsgEndAccelRail>(MessageID) */ = delete;
	};
}