#pragma once

namespace app::game
{
	class MsgEventMenu : public hh::fnd::MessageAsyncHandlerInplace<MsgEventMenu>, public fnd::AppMessage<MsgEventMenu>
	{
	private:
		inline static uint32_t MessageID = 0x2164;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEventMenu() /* : fnd::AppMessage<MsgEventMenu>(MessageID) */ = delete;
	};
}