#pragma once

namespace app
{
	class MsgEndReflexesPanel : public hh::fnd::MessageAsyncHandlerInplace<MsgEndReflexesPanel>, public fnd::AppMessage<MsgEndReflexesPanel>
	{
	private:
		inline static uint32_t MessageID = 0x2149;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndReflexesPanel() /* : fnd::AppMessage<MsgEndReflexesPanel>(MessageID) */ = delete;
	};
}