#pragma once

namespace app
{
	class MsgEndMasterTrial : public hh::fnd::MessageAsyncHandlerInplace<MsgEndMasterTrial>, public fnd::AppMessage<MsgEndMasterTrial>
	{
	private:
		inline static uint32_t MessageID = 0x2139;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndMasterTrial() /* : fnd::AppMessage<MsgEndMasterTrial>(MessageID) */ = delete;
	};
}