#pragma once

namespace app
{
	class MsgElementBulletEnemyDamage : public hh::fnd::MessageAsyncHandlerInplace<MsgElementBulletEnemyDamage>, public fnd::AppMessage<MsgElementBulletEnemyDamage>
	{
	private:
		inline static uint32_t MessageID = 0x2111;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(72);

		MsgElementBulletEnemyDamage() /* : fnd::AppMessage<MsgElementBulletEnemyDamage>(MessageID) */ = delete;
	};
}