#pragma once

namespace app
{
	class MsgEndBattle : public hh::fnd::MessageAsyncHandlerInplace<MsgEndBattle>, public fnd::AppMessage<MsgEndBattle>
	{
	private:
		inline static uint32_t MessageID = 0x211E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndBattle() /* : fnd::AppMessage<MsgEndBattle>(MessageID) */ = delete;
	};
}