#pragma once

namespace app
{
	class MsgExpandChaosEmerald : public hh::fnd::MessageAsyncHandlerInplace<MsgExpandChaosEmerald>, public fnd::AppMessage<MsgExpandChaosEmerald>
	{
	private:
		inline static uint32_t MessageID = 0x216D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgExpandChaosEmerald() /* : fnd::AppMessage<MsgExpandChaosEmerald>(MessageID) */ = delete;
	};
}