#pragma once

namespace app
{
	class MsgEndKodamaSticked : public hh::fnd::MessageAsyncHandlerInplace<MsgEndKodamaSticked>, public fnd::AppMessage<MsgEndKodamaSticked>
	{
	private:
		inline static uint32_t MessageID = 0x2138;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndKodamaSticked() /* : fnd::AppMessage<MsgEndKodamaSticked>(MessageID) */ = delete;
	};
}