#pragma once

namespace app
{
	class MsgEndCyBlasterLift : public hh::fnd::MessageAsyncHandlerInplace<MsgEndCyBlasterLift>, public fnd::AppMessage<MsgEndCyBlasterLift>
	{
	private:
		inline static uint32_t MessageID = 0x212B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(56);

		MsgEndCyBlasterLift() /* : fnd::AppMessage<MsgEndCyBlasterLift>(MessageID) */ = delete;
	};
}