#pragma once

namespace app::player
{
	class MsgEndExternalControl : public hh::fnd::MessageAsyncHandlerInplace<MsgEndExternalControl>, public fnd::AppMessage<MsgEndExternalControl>
	{
	private:
		inline static uint32_t MessageID = 0x2130;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgEndExternalControl() /* : fnd::AppMessage<MsgEndExternalControl>(MessageID) */ = delete;
	};
}