#pragma once

namespace app
{
	class MsgEndBossQTE : public hh::fnd::MessageAsyncHandlerInplace<MsgEndBossQTE>, public fnd::AppMessage<MsgEndBossQTE>
	{
	private:
		inline static uint32_t MessageID = 0x2126;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndBossQTE() /* : fnd::AppMessage<MsgEndBossQTE>(MessageID) */ = delete;
	};
}