#pragma once

namespace app::player
{
	class MsgEndDrift : public hh::fnd::MessageAsyncHandlerInplace<MsgEndDrift>, public fnd::AppMessage<MsgEndDrift>
	{
	private:
		inline static uint32_t MessageID = 0x212D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgEndDrift() /* : fnd::AppMessage<MsgEndDrift>(MessageID) */ = delete;
	};
}