#pragma once

namespace app
{
	class MsgGetNumTimesToFall : public hh::fnd::MessageAsyncHandlerInplace<MsgGetNumTimesToFall>, public fnd::AppMessage<MsgGetNumTimesToFall>
	{
	private:
		inline static uint32_t MessageID = 0x219B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgGetNumTimesToFall() /* : fnd::AppMessage<MsgGetNumTimesToFall>(MessageID) */ = delete;
	};
}