#pragma once

namespace app
{
	class MsgGimmickControlSignal : public hh::fnd::MessageAsyncHandlerInplace<MsgGimmickControlSignal>, public fnd::AppMessage<MsgGimmickControlSignal>
	{
	private:
		inline static uint32_t MessageID = 0x21B2;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgGimmickControlSignal() /* : fnd::AppMessage<MsgGimmickControlSignal>(MessageID) */ = delete;
	};
}