#pragma once

namespace app::game
{
	class MsgGetPracticeTimer : public hh::fnd::MessageAsyncHandlerInplace<MsgGetPracticeTimer>, public fnd::AppMessage<MsgGetPracticeTimer>
	{
	private:
		inline static uint32_t MessageID = 0x219E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgGetPracticeTimer() /* : fnd::AppMessage<MsgGetPracticeTimer>(MessageID) */ = delete;
	};
}