#pragma once

namespace app
{
	class MsgGetRailInfoClosestToSonic : public hh::fnd::MessageAsyncHandlerInplace<MsgGetRailInfoClosestToSonic>, public fnd::AppMessage<MsgGetRailInfoClosestToSonic>
	{
	private:
		inline static uint32_t MessageID = 0x21A1;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgGetRailInfoClosestToSonic() /* : fnd::AppMessage<MsgGetRailInfoClosestToSonic>(MessageID) */ = delete;
	};
}