#pragma once

namespace app
{
	class MsgGetClosestPointOnRail : public hh::fnd::MessageAsyncHandlerInplace<MsgGetClosestPointOnRail>, public fnd::AppMessage<MsgGetClosestPointOnRail>
	{
	private:
		inline static uint32_t MessageID = 0x2188;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(56);

		MsgGetClosestPointOnRail() /* : fnd::AppMessage<MsgGetClosestPointOnRail>(MessageID) */ = delete;
	};
}