#pragma once

namespace app
{
	class MsgHideMistakeCounter : public hh::fnd::MessageAsyncHandlerInplace<MsgHideMistakeCounter>, public fnd::AppMessage<MsgHideMistakeCounter>
	{
	private:
		inline static uint32_t MessageID = 0x21D5;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgHideMistakeCounter() /* : fnd::AppMessage<MsgHideMistakeCounter>(MessageID) */ = delete;
	};
}