#pragma once

namespace app
{
	class MsgIsTakeNumberRing : public hh::fnd::MessageAsyncHandlerInplace<MsgIsTakeNumberRing>, public fnd::AppMessage<MsgIsTakeNumberRing>
	{
	private:
		inline static uint32_t MessageID = 0x21E3;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgIsTakeNumberRing() /* : fnd::AppMessage<MsgIsTakeNumberRing>(MessageID) */ = delete;
	};
}