#pragma once

namespace app
{
	class MsgKnightIncidentGetFlyerStatus : public hh::fnd::MessageAsyncHandlerInplace<MsgKnightIncidentGetFlyerStatus>, public fnd::AppMessage<MsgKnightIncidentGetFlyerStatus>
	{
	private:
		inline static uint32_t MessageID = 0x21ED;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgKnightIncidentGetFlyerStatus() /* : fnd::AppMessage<MsgKnightIncidentGetFlyerStatus>(MessageID) */ = delete;
	};
}