#pragma once

namespace app
{
	class MsgKodamaSticked : public hh::fnd::MessageAsyncHandlerInplace<MsgKodamaSticked>, public fnd::AppMessage<MsgKodamaSticked>
	{
	private:
		inline static uint32_t MessageID = 0x21F0;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgKodamaSticked() /* : fnd::AppMessage<MsgKodamaSticked>(MessageID) */ = delete;
	};
}