#pragma once

namespace app
{
	class MsgMiniBossTrackerBaseRebirth : public hh::fnd::MessageAsyncHandlerInplace<MsgMiniBossTrackerBaseRebirth>, public fnd::AppMessage<MsgMiniBossTrackerBaseRebirth>
	{
	private:
		inline static uint32_t MessageID = 0x2217;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgMiniBossTrackerBaseRebirth() /* : fnd::AppMessage<MsgMiniBossTrackerBaseRebirth>(MessageID) */ = delete;
	};
}