#pragma once

namespace app::move
{
	class MsgMovementLeaveGround : public hh::fnd::MessageAsyncHandlerInplace<MsgMovementLeaveGround>, public fnd::AppMessage<MsgMovementLeaveGround>
	{
	private:
		inline static uint32_t MessageID = 0x2220;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgMovementLeaveGround() /* : fnd::AppMessage<MsgMovementLeaveGround>(MessageID) */ = delete;
	};
}