#pragma once

namespace app::move
{
	class MsgMovementFindTarget : public hh::fnd::MessageAsyncHandlerInplace<MsgMovementFindTarget>, public fnd::AppMessage<MsgMovementFindTarget>
	{
	private:
		inline static uint32_t MessageID = 0x221F;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgMovementFindTarget() /* : fnd::AppMessage<MsgMovementFindTarget>(MessageID) */ = delete;
	};
}