#pragma once

namespace app::player
{
	class MsgNotifySlingshotReadyCancel : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifySlingshotReadyCancel>, public fnd::AppMessage<MsgNotifySlingshotReadyCancel>
	{
	private:
		inline static uint32_t MessageID = 0x2259;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifySlingshotReadyCancel() /* : fnd::AppMessage<MsgNotifySlingshotReadyCancel>(MessageID) */ = delete;
	};
}