#pragma once

namespace app
{
	class MsgNotifyHackingEnemyDead : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifyHackingEnemyDead>, public fnd::AppMessage<MsgNotifyHackingEnemyDead>
	{
	private:
		inline static uint32_t MessageID = 0x2248;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifyHackingEnemyDead() /* : fnd::AppMessage<MsgNotifyHackingEnemyDead>(MessageID) */ = delete;
	};
}