#pragma once

namespace app::player
{
	class MsgNotifyEndExternalControl : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifyEndExternalControl>, public fnd::AppMessage<MsgNotifyEndExternalControl>
	{
	private:
		inline static uint32_t MessageID = 0x223C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifyEndExternalControl() /* : fnd::AppMessage<MsgNotifyEndExternalControl>(MessageID) */ = delete;
	};
}