#pragma once

namespace app
{
	class MsgNotifyDashCircleJump : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifyDashCircleJump>, public fnd::AppMessage<MsgNotifyDashCircleJump>
	{
	private:
		inline static uint32_t MessageID = 0x2235;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifyDashCircleJump() /* : fnd::AppMessage<MsgNotifyDashCircleJump>(MessageID) */ = delete;
	};
}