#pragma once

namespace app::player
{
	class MsgNotifyEndFallCyberSpace : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifyEndFallCyberSpace>, public fnd::AppMessage<MsgNotifyEndFallCyberSpace>
	{
	private:
		inline static uint32_t MessageID = 0x223D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifyEndFallCyberSpace() /* : fnd::AppMessage<MsgNotifyEndFallCyberSpace>(MessageID) */ = delete;
	};
}