#pragma once

namespace app::player
{
	class MsgNotifySlingshotReadyStart : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifySlingshotReadyStart>, public fnd::AppMessage<MsgNotifySlingshotReadyStart>
	{
	private:
		inline static uint32_t MessageID = 0x225A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifySlingshotReadyStart() /* : fnd::AppMessage<MsgNotifySlingshotReadyStart>(MessageID) */ = delete;
	};
}