#pragma once

namespace app::player
{
	class MsgNotifySpannerThrow : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifySpannerThrow>, public fnd::AppMessage<MsgNotifySpannerThrow>
	{
	private:
		inline static uint32_t MessageID = 0x225B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgNotifySpannerThrow() /* : fnd::AppMessage<MsgNotifySpannerThrow>(MessageID) */ = delete;
	};
}