#pragma once

namespace app
{
	class MsgNotifyGetSlotStar : public hh::fnd::MessageAsyncHandlerInplace<MsgNotifyGetSlotStar>, public fnd::AppMessage<MsgNotifyGetSlotStar>
	{
	private:
		inline static uint32_t MessageID = 0x2247;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgNotifyGetSlotStar() /* : fnd::AppMessage<MsgNotifyGetSlotStar>(MessageID) */ = delete;
	};
}