#pragma once

namespace app
{
	class MsgOnGroundImpulse : public hh::fnd::MessageAsyncHandlerInplace<MsgOnGroundImpulse>, public fnd::AppMessage<MsgOnGroundImpulse>
	{
	private:
		inline static uint32_t MessageID = 0x2270;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(136);

		MsgOnGroundImpulse() /* : fnd::AppMessage<MsgOnGroundImpulse>(MessageID) */ = delete;
	};
}