#pragma once

namespace app::player
{
	class MsgPlayerInputEnabled : public hh::fnd::MessageAsyncHandlerInplace<MsgPlayerInputEnabled>, public fnd::AppMessage<MsgPlayerInputEnabled>
	{
	private:
		inline static uint32_t MessageID = 0x2283;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgPlayerInputEnabled() /* : fnd::AppMessage<MsgPlayerInputEnabled>(MessageID) */ = delete;
	};
}