#pragma once

namespace app::game
{
	class MsgPhotoModeEnd : public hh::fnd::MessageAsyncHandlerInplace<MsgPhotoModeEnd>, public fnd::AppMessage<MsgPhotoModeEnd>
	{
	private:
		inline static uint32_t MessageID = 0x227B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgPhotoModeEnd() /* : fnd::AppMessage<MsgPhotoModeEnd>(MessageID) */ = delete;
	};
}