#pragma once

namespace app
{
	class MsgPlayerFinishReturn : public hh::fnd::MessageAsyncHandlerInplace<MsgPlayerFinishReturn>, public fnd::AppMessage<MsgPlayerFinishReturn>
	{
	private:
		inline static uint32_t MessageID = 0x2282;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgPlayerFinishReturn() /* : fnd::AppMessage<MsgPlayerFinishReturn>(MessageID) */ = delete;
	};
}