#pragma once

namespace app::camera
{
	class MsgPopCameraClassicParam : public hh::fnd::MessageAsyncHandlerInplace<MsgPopCameraClassicParam>, public fnd::AppMessage<MsgPopCameraClassicParam>
	{
	private:
		inline static uint32_t MessageID = 0x228B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgPopCameraClassicParam() /* : fnd::AppMessage<MsgPopCameraClassicParam>(MessageID) */ = delete;
	};
}