#pragma once

namespace app::game
{
	class MsgPhotoModeStart : public hh::fnd::MessageAsyncHandlerInplace<MsgPhotoModeStart>, public fnd::AppMessage<MsgPhotoModeStart>
	{
	private:
		inline static uint32_t MessageID = 0x227C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgPhotoModeStart() /* : fnd::AppMessage<MsgPhotoModeStart>(MessageID) */ = delete;
	};
}