#pragma once

namespace app
{
	class MsgParriedObject : public hh::fnd::MessageAsyncHandlerInplace<MsgParriedObject>, public fnd::AppMessage<MsgParriedObject>
	{
	private:
		inline static uint32_t MessageID = 0x2275;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgParriedObject() /* : fnd::AppMessage<MsgParriedObject>(MessageID) */ = delete;
	};
}