#pragma once

namespace app::game
{
	class MsgPreparePracticeTimer : public hh::fnd::MessageAsyncHandlerInplace<MsgPreparePracticeTimer>, public fnd::AppMessage<MsgPreparePracticeTimer>
	{
	private:
		inline static uint32_t MessageID = 0x228D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgPreparePracticeTimer() /* : fnd::AppMessage<MsgPreparePracticeTimer>(MessageID) */ = delete;
	};
}