#pragma once

namespace app::camera
{
	class MsgPushCameraClassicParam : public hh::fnd::MessageAsyncHandlerInplace<MsgPushCameraClassicParam>, public fnd::AppMessage<MsgPushCameraClassicParam>
	{
	private:
		inline static uint32_t MessageID = 0x2291;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgPushCameraClassicParam() /* : fnd::AppMessage<MsgPushCameraClassicParam>(MessageID) */ = delete;
	};
}