#pragma once

namespace app
{
	class MsgRegisterTimeStopObject : public hh::fnd::MessageAsyncHandlerInplace<MsgRegisterTimeStopObject>, public fnd::AppMessage<MsgRegisterTimeStopObject>
	{
	private:
		inline static uint32_t MessageID = 0x22A6;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgRegisterTimeStopObject() /* : fnd::AppMessage<MsgRegisterTimeStopObject>(MessageID) */ = delete;
	};
}