#pragma once

namespace app
{
	class MsgReflexesPanelOff : public hh::fnd::MessageAsyncHandlerInplace<MsgReflexesPanelOff>, public fnd::AppMessage<MsgReflexesPanelOff>
	{
	private:
		inline static uint32_t MessageID = 0x22A2;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgReflexesPanelOff() /* : fnd::AppMessage<MsgReflexesPanelOff>(MessageID) */ = delete;
	};
}