#pragma once

namespace app::player
{
	class MsgSetPlayerCollisionEnabled : public hh::fnd::MessageAsyncHandlerInplace<MsgSetPlayerCollisionEnabled>, public fnd::AppMessage<MsgSetPlayerCollisionEnabled>
	{
	private:
		inline static uint32_t MessageID = 0x22F6;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgSetPlayerCollisionEnabled() /* : fnd::AppMessage<MsgSetPlayerCollisionEnabled>(MessageID) */ = delete;
	};
}