#pragma once

namespace app::player
{
	class MsgSpannerFloatTouching : public hh::fnd::MessageAsyncHandlerInplace<MsgSpannerFloatTouching>, public fnd::AppMessage<MsgSpannerFloatTouching>
	{
	private:
		inline static uint32_t MessageID = 0x2319;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgSpannerFloatTouching() /* : fnd::AppMessage<MsgSpannerFloatTouching>(MessageID) */ = delete;
	};
}