#pragma once

namespace app
{
	class MsgSpawnHackingEnemy : public hh::fnd::MessageAsyncHandlerInplace<MsgSpawnHackingEnemy>, public fnd::AppMessage<MsgSpawnHackingEnemy>
	{
	private:
		inline static uint32_t MessageID = 0x231A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgSpawnHackingEnemy() /* : fnd::AppMessage<MsgSpawnHackingEnemy>(MessageID) */ = delete;
	};
}