#pragma once

namespace app::player
{
	class MsgSetGrindSpeed : public hh::fnd::MessageAsyncHandlerInplace<MsgSetGrindSpeed>, public fnd::AppMessage<MsgSetGrindSpeed>
	{
	private:
		inline static uint32_t MessageID = 0x22F0;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(24);

		MsgSetGrindSpeed() /* : fnd::AppMessage<MsgSetGrindSpeed>(MessageID) */ = delete;
	};
}