#pragma once

namespace app
{
	class MsgSkierMissileNotifyExploded : public hh::fnd::MessageAsyncHandlerInplace<MsgSkierMissileNotifyExploded>, public fnd::AppMessage<MsgSkierMissileNotifyExploded>
	{
	private:
		inline static uint32_t MessageID = 0x2313;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgSkierMissileNotifyExploded() /* : fnd::AppMessage<MsgSkierMissileNotifyExploded>(MessageID) */ = delete;
	};
}