#pragma once

namespace app
{
	class MsgSetEnabledRailBulletCamera : public hh::fnd::MessageAsyncHandlerInplace<MsgSetEnabledRailBulletCamera>, public fnd::AppMessage<MsgSetEnabledRailBulletCamera>
	{
	private:
		inline static uint32_t MessageID = 0x22EF;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgSetEnabledRailBulletCamera() /* : fnd::AppMessage<MsgSetEnabledRailBulletCamera>(MessageID) */ = delete;
	};
}