#pragma once

namespace app
{
	class MsgShotgunTouchStartSpecialCamera : public hh::fnd::MessageAsyncHandlerInplace<MsgShotgunTouchStartSpecialCamera>, public fnd::AppMessage<MsgShotgunTouchStartSpecialCamera>
	{
	private:
		inline static uint32_t MessageID = 0x230C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgShotgunTouchStartSpecialCamera() /* : fnd::AppMessage<MsgShotgunTouchStartSpecialCamera>(MessageID) */ = delete;
	};
}