#pragma once

namespace app::player
{
	class MsgSetAbilityEnabled : public hh::fnd::MessageAsyncHandlerInplace<MsgSetAbilityEnabled>, public fnd::AppMessage<MsgSetAbilityEnabled>
	{
	private:
		inline static uint32_t MessageID = 0x22E4;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgSetAbilityEnabled() /* : fnd::AppMessage<MsgSetAbilityEnabled>(MessageID) */ = delete;
	};
}