#pragma once

namespace app::camera
{
	class MsgShakeCameraEnd : public hh::fnd::MessageAsyncHandlerInplace<MsgShakeCameraEnd>, public fnd::AppMessage<MsgShakeCameraEnd>
	{
	private:
		inline static uint32_t MessageID = 0x22FE;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgShakeCameraEnd() /* : fnd::AppMessage<MsgShakeCameraEnd>(MessageID) */ = delete;
	};
}