#pragma once

namespace app::player
{
	class MsgSetSandSkiReleaseEnabled : public hh::fnd::MessageAsyncHandlerInplace<MsgSetSandSkiReleaseEnabled>, public fnd::AppMessage<MsgSetSandSkiReleaseEnabled>
	{
	private:
		inline static uint32_t MessageID = 0x22F7;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgSetSandSkiReleaseEnabled() /* : fnd::AppMessage<MsgSetSandSkiReleaseEnabled>(MessageID) */ = delete;
	};
}