#pragma once

namespace app::game
{
	class MsgScriptExit : public hh::fnd::MessageAsyncHandlerInplace<MsgScriptExit>, public fnd::AppMessage<MsgScriptExit>
	{
	private:
		inline static uint32_t MessageID = 0x22E2;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgScriptExit() /* : fnd::AppMessage<MsgScriptExit>(MessageID) */ = delete;
	};
}