#pragma once

namespace app
{
	class MsgTutorialEndCheckWallRun : public hh::fnd::MessageAsyncHandlerInplace<MsgTutorialEndCheckWallRun>, public fnd::AppMessage<MsgTutorialEndCheckWallRun>
	{
	private:
		inline static uint32_t MessageID = 0x2386;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTutorialEndCheckWallRun() /* : fnd::AppMessage<MsgTutorialEndCheckWallRun>(MessageID) */ = delete;
	};
}