#pragma once

namespace app
{
	class MsgTakeQuestItem : public hh::fnd::MessageAsyncHandlerInplace<MsgTakeQuestItem>, public fnd::AppMessage<MsgTakeQuestItem>
	{
	private:
		inline static uint32_t MessageID = 0x2360;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTakeQuestItem() /* : fnd::AppMessage<MsgTakeQuestItem>(MessageID) */ = delete;
	};
}