#pragma once

namespace app::tutorial
{
	class MsgTutorialEndCheckCutGrass : public hh::fnd::MessageAsyncHandlerInplace<MsgTutorialEndCheckCutGrass>, public fnd::AppMessage<MsgTutorialEndCheckCutGrass>
	{
	private:
		inline static uint32_t MessageID = 0x2385;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTutorialEndCheckCutGrass() /* : fnd::AppMessage<MsgTutorialEndCheckCutGrass>(MessageID) */ = delete;
	};
}