#pragma once

namespace app::game
{
	class MsgTransitHackingStage : public hh::fnd::MessageAsyncHandlerInplace<MsgTransitHackingStage>, public fnd::AppMessage<MsgTransitHackingStage>
	{
	private:
		inline static uint32_t MessageID = 0x237B;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(88);

		MsgTransitHackingStage() /* : fnd::AppMessage<MsgTransitHackingStage>(MessageID) */ = delete;
	};
}