#pragma once

namespace app::tutorial
{
	class MsgTutorialStartCheckCutGrass : public hh::fnd::MessageAsyncHandlerInplace<MsgTutorialStartCheckCutGrass>, public fnd::AppMessage<MsgTutorialStartCheckCutGrass>
	{
	private:
		inline static uint32_t MessageID = 0x238A;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTutorialStartCheckCutGrass() /* : fnd::AppMessage<MsgTutorialStartCheckCutGrass>(MessageID) */ = delete;
	};
}