#pragma once

namespace app::game
{
	class MsgTimeUp : public hh::fnd::MessageAsyncHandlerInplace<MsgTimeUp>, public fnd::AppMessage<MsgTimeUp>
	{
	private:
		inline static uint32_t MessageID = 0x2370;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTimeUp() /* : fnd::AppMessage<MsgTimeUp>(MessageID) */ = delete;
	};
}