#pragma once

namespace app
{
	class MsgTutorialStartWallRun : public hh::fnd::MessageAsyncHandlerInplace<MsgTutorialStartWallRun>, public fnd::AppMessage<MsgTutorialStartWallRun>
	{
	private:
		inline static uint32_t MessageID = 0x238C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgTutorialStartWallRun() /* : fnd::AppMessage<MsgTutorialStartWallRun>(MessageID) */ = delete;
	};
}