#pragma once

namespace app::game
{
	class MsgTransitExtraIslandStage : public hh::fnd::MessageAsyncHandlerInplace<MsgTransitExtraIslandStage>, public fnd::AppMessage<MsgTransitExtraIslandStage>
	{
	private:
		inline static uint32_t MessageID = 0x2379;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgTransitExtraIslandStage() /* : fnd::AppMessage<MsgTransitExtraIslandStage>(MessageID) */ = delete;
	};
}