#pragma once

namespace app::player
{
	class MsgTakeNitroBoost : public hh::fnd::MessageAsyncHandlerInplace<MsgTakeNitroBoost>, public fnd::AppMessage<MsgTakeNitroBoost>
	{
	private:
		inline static uint32_t MessageID = 0x235D;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgTakeNitroBoost() /* : fnd::AppMessage<MsgTakeNitroBoost>(MessageID) */ = delete;
	};
}