#pragma once

namespace app::ui
{
	class MsgUITimingGaugeBegin : public hh::fnd::MessageAsyncHandlerInplace<MsgUITimingGaugeBegin>, public fnd::AppMessage<MsgUITimingGaugeBegin>
	{
	private:
		inline static uint32_t MessageID = 0x241C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(16);

		MsgUITimingGaugeBegin() /* : fnd::AppMessage<MsgUITimingGaugeBegin>(MessageID) */ = delete;
	};
}