#pragma once

namespace app::ui
{
	class MsgUIJumpSelectorOff : public hh::fnd::MessageAsyncHandlerInplace<MsgUIJumpSelectorOff>, public fnd::AppMessage<MsgUIJumpSelectorOff>
	{
	private:
		inline static uint32_t MessageID = 0x23C4;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUIJumpSelectorOff() /* : fnd::AppMessage<MsgUIJumpSelectorOff>(MessageID) */ = delete;
	};
}