#pragma once

namespace app::ui
{
	class MsgUIGetQuestMag : public hh::fnd::MessageAsyncHandlerInplace<MsgUIGetQuestMag>, public fnd::AppMessage<MsgUIGetQuestMag>
	{
	private:
		inline static uint32_t MessageID = 0x23BA;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgUIGetQuestMag() /* : fnd::AppMessage<MsgUIGetQuestMag>(MessageID) */ = delete;
	};
}