#pragma once

namespace app::ui
{
	class MsgUISelectCannonOn : public hh::fnd::MessageAsyncHandlerInplace<MsgUISelectCannonOn>, public fnd::AppMessage<MsgUISelectCannonOn>
	{
	private:
		inline static uint32_t MessageID = 0x2403;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(40);

		MsgUISelectCannonOn() /* : fnd::AppMessage<MsgUISelectCannonOn>(MessageID) */ = delete;
	};
}