#pragma once

namespace app::ui
{
	class MsgUIActionChainAddScore : public hh::fnd::MessageAsyncHandlerInplace<MsgUIActionChainAddScore>, public fnd::AppMessage<MsgUIActionChainAddScore>
	{
	private:
		inline static uint32_t MessageID = 0x238E;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgUIActionChainAddScore() /* : fnd::AppMessage<MsgUIActionChainAddScore>(MessageID) */ = delete;
	};
}