#pragma once

namespace app::ui
{
	class MsgUIHackingEndGage : public hh::fnd::MessageAsyncHandlerInplace<MsgUIHackingEndGage>, public fnd::AppMessage<MsgUIHackingEndGage>
	{
	private:
		inline static uint32_t MessageID = 0x23BC;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUIHackingEndGage() /* : fnd::AppMessage<MsgUIHackingEndGage>(MessageID) */ = delete;
	};
}