#pragma once

namespace app::ui
{
	class MsgUIMiniResultOff : public hh::fnd::MessageAsyncHandlerInplace<MsgUIMiniResultOff>, public fnd::AppMessage<MsgUIMiniResultOff>
	{
	private:
		inline static uint32_t MessageID = 0x23DF;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUIMiniResultOff() /* : fnd::AppMessage<MsgUIMiniResultOff>(MessageID) */ = delete;
	};
}