#pragma once

namespace app::ui
{
	class MsgUISetupAnimal : public hh::fnd::MessageAsyncHandlerInplace<MsgUISetupAnimal>, public fnd::AppMessage<MsgUISetupAnimal>
	{
	private:
		inline static uint32_t MessageID = 0x2410;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUISetupAnimal() /* : fnd::AppMessage<MsgUISetupAnimal>(MessageID) */ = delete;
	};
}