#pragma once

namespace app::ui
{
	class MsgUIMainMenuQuit : public hh::fnd::MessageAsyncHandlerInplace<MsgUIMainMenuQuit>, public fnd::AppMessage<MsgUIMainMenuQuit>
	{
	private:
		inline static uint32_t MessageID = 0x23D5;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUIMainMenuQuit() /* : fnd::AppMessage<MsgUIMainMenuQuit>(MessageID) */ = delete;
	};
}