#pragma once

namespace app::ui
{
	class MsgUIFishingPortalActivate : public hh::fnd::MessageAsyncHandlerInplace<MsgUIFishingPortalActivate>, public fnd::AppMessage<MsgUIFishingPortalActivate>
	{
	private:
		inline static uint32_t MessageID = 0x23B0;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(56);

		MsgUIFishingPortalActivate() /* : fnd::AppMessage<MsgUIFishingPortalActivate>(MessageID) */ = delete;
	};
}