#pragma once

namespace app::ui
{
	class MsgUISelectCannonOff : public hh::fnd::MessageAsyncHandlerInplace<MsgUISelectCannonOff>, public fnd::AppMessage<MsgUISelectCannonOff>
	{
	private:
		inline static uint32_t MessageID = 0x2402;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgUISelectCannonOff() /* : fnd::AppMessage<MsgUISelectCannonOff>(MessageID) */ = delete;
	};
}