#pragma once

namespace app::ui
{
	class MsgUILockonView : public hh::fnd::MessageAsyncHandlerInplace<MsgUILockonView>, public fnd::AppMessage<MsgUILockonView>
	{
	private:
		inline static uint32_t MessageID = 0x23CE;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(72);

		MsgUILockonView() /* : fnd::AppMessage<MsgUILockonView>(MessageID) */ = delete;
	};
}