#pragma once

namespace app::ui
{
	class MsgUIPinballUpdateRate : public hh::fnd::MessageAsyncHandlerInplace<MsgUIPinballUpdateRate>, public fnd::AppMessage<MsgUIPinballUpdateRate>
	{
	private:
		inline static uint32_t MessageID = 0x23F1;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgUIPinballUpdateRate() /* : fnd::AppMessage<MsgUIPinballUpdateRate>(MessageID) */ = delete;
	};
}