#pragma once

namespace app::ui
{
	class MsgUIExclamation : public hh::fnd::MessageAsyncHandlerInplace<MsgUIExclamation>, public fnd::AppMessage<MsgUIExclamation>
	{
	private:
		inline static uint32_t MessageID = 0x23AD;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgUIExclamation() /* : fnd::AppMessage<MsgUIExclamation>(MessageID) */ = delete;
	};
}