#pragma once

namespace app
{
	class MsgVanishPowerupSeed : public hh::fnd::MessageAsyncHandlerInplace<MsgVanishPowerupSeed>, public fnd::AppMessage<MsgVanishPowerupSeed>
	{
	private:
		inline static uint32_t MessageID = 0x242F;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.

		MsgVanishPowerupSeed() /* : fnd::AppMessage<MsgVanishPowerupSeed>(MessageID) */ = delete;
	};
}