#pragma once

namespace app
{
	class MsgWolfRegistHandle : public hh::fnd::MessageAsyncHandlerInplace<MsgWolfRegistHandle>, public fnd::AppMessage<MsgWolfRegistHandle>
	{
	private:
		inline static uint32_t MessageID = 0x244C;

	public:
		// This class, and its size was auto-generated by ĐeäTh and is lacking documentation.
		// Before using ensure that the size matches the size from the game and create a matching constructor.
		// After those steps the delete call on the constructor can be deleted and the base class constructor can be called normally.
		INSERT_PADDING(8);

		MsgWolfRegistHandle() /* : fnd::AppMessage<MsgWolfRegistHandle>(MessageID) */ = delete;
	};
}